CORS_ORIGIN=*
CORS_METHOD=*
MARKETPLACE_SUBGRAPH_URL=https://api.thegraph.com/subgraphs/name/decentraland/marketplace
COLLECTIONS_SUBGRAPH_URL=https://api.thegraph.com/subgraphs/name/decentraland/collections-matic-mainnet
RENTALS_SUBGRAPH_URL=https://api.thegraph.com/subgraphs/name/decentraland/rentals-ethereum-mainnet
SIGNATURES_SERVER_URL=http://localhost:3000
MARKETPLACE_FAVORITES_SERVER_URL=http://localhost:3000
BUILDER_PG_COMPONENT_PSQL_DATABASE=builder
BUILDER_PG_COMPONENT_PSQL_PORT=8020
BUILDER_PG_COMPONENT_PSQL_HOST=localhost
BUILDER_PG_COMPONENT_PSQL_USER=user
BUILDER_PG_COMPONENT_PSQL_PASSWORD=password
MARKETPLACE_CHAIN_ID=3
COLLECTIONS_CHAIN_ID=137

API_VERSION=v1
HTTP_SERVER_PORT=5005
HTTP_SERVER_HOST=0.0.0.0
